steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - CadeiaAjuda.Web/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - ApiBaseUrl=${_API_BASE_URL}

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: cadeia-ajuda-web
  _REGION: us-central1
  _REPOSITORY: cloud-run-source-deploy
  _IMAGE: cadeia-ajuda-web
  _API_BASE_URL: https://cadeia-ajuda-api-677662115710.us-central1.run.app
